traffic_dbt:
  target: dev
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: warehouse
      pass: warehouse
      dbname: warehouse
      schema: warehouse

    prod:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: warehouse
      pass: warehouse
      dbname: warehouse
      schema: warehouse

